---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - 'recipe[apt::default]'
  - name: centos-6.7
  - name: centos-7.2
suites:
  - name: source_build
    run_list:
      - 'recipe[cobblerd::source]'
      - 'recipe[cobblerd::default]'
  - name: package_install
    run_list:
      - 'recipe[cobblerd::package]'
      - 'recipe[cobblerd::default]'
  - name: images
    run_list:
      - 'recipe[cobblerd::centos]'
      - 'recipe[cobblerd::ubuntu]'
  - name: web
    run_list:
      - 'recipe[cobblerd::web]'
    excludes:
      - centos-5.11
